NeroMerch/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NeroMerch.Manager;
using NeroMerch.Models;

namespace NeroMerch.Controllers
{
    public class CartController : Controller
    {
        [HttpGet]
        [Authorize]
        public ActionResult Show()
        {
            //Warenkorb aus Session holen
            var mgr = Session.GetCart();

            //Daten aus Datenbank laden
            var dbProducts = mgr.GetProducts();

            //In Viewmodel mappen
            var vm = new ShowVm();

            foreach (var dbProduct in dbProducts)
            {
                var vmProduct = new ShowVmProduct();
                vmProduct.CompanyName = dbProduct.Manufacturer;
                vmProduct.Id = dbProduct.Id;
                vmProduct.ImagePath = dbProduct.ImagePath;
                vmProduct.Name = dbProduct.ProductName;
                vmProduct.UnitPrice = dbProduct.NetUnitPrice;

                vmProduct.Quantity = mgr.Cart[dbProduct.Id]; //todo in Cart-Methode kapseln
                vmProduct.LinePrice = dbProduct.NetUnitPrice * vmProduct.Quantity; //todo in Cart-Methode kapseln

                vm.Products.Add(vmProduct);
            }

            vm.TotalPrice = vm.Products.Sum(p => p.LinePrice);

            //Viewmodel an View übergeben
            return View(vm);
        }

        [HttpPost]
        [Authorize]
        public ActionResult ChangeQty(int prodId, int qty, bool? info)
        {
            if (info == null)
            {
                var mgr = Session.GetCart();
                mgr.Remove(prodId);
                Session.SaveCart(mgr);
            }
            else if (info == true)
            {
                Add(prodId, qty);
            }
            else
            {
                Remove(prodId, qty);
            }

            return RedirectToAction("Show");
        }

        [HttpPost]
        [Authorize]
        public ActionResult Add(int prodId, int qty)
        {
            var mgr = Session.GetCart();

            mgr.Add(prodId, qty);

            Session.SaveCart(mgr);

            return RedirectToAction("Overview", "Product");
        }

        [HttpPost]
        [Authorize]
        public ActionResult Remove(int prodId, int qty)
        {
            var mgr = Session.GetCart();

            mgr.Remove(prodId, qty);

            Session.SaveCart(mgr);

            return RedirectToAction("Overview", "Product");
        }
    }

    public static class SessionExtensions
    {
        public static CartManager GetCart(this HttpSessionStateBase session)
        {
            return new CartManager((Dictionary<int, int>)session["CART"]);
        }

        public static void SaveCart(this HttpSessionStateBase session, CartManager mgr)
        {
            session["CART"] = mgr.Cart;
        }
    }
}

NeroMerch/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NeroMerch.DATA;
using NeroMerch.Manager;
using NeroMerch.Models;
using System.Web.Security;

namespace NeroMerch.Controllers
{
   
    public class CustomerController : Controller
    {
        
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Register(RegisterVM vmReg)
        {
            if (!vmReg.AcceptedTerms)
            {
                //Fehlermeldung ausgeben
                return View();
            }

            if (vmReg.Passwort != vmReg.Passwort_bestätigen)
            {
                //Fehlermeldung ausgeben
                return View();
            }

            //Mappen von Viewmodel auf Datenbankmodel (Entitätsmodel)
            var newCustomer = new Customer();

            newCustomer.City = vmReg.City;
            newCustomer.Email = vmReg.Email;
            newCustomer.FirstName = vmReg.FirstName;
            newCustomer.LastName = vmReg.LastName;
            newCustomer.Street = vmReg.Street;
            newCustomer.Title = vmReg.Title;
            newCustomer.Zip = vmReg.Zip;

            //newUser.Id = ; //Wird von DB zugewiesen
            //newUser.PasswordHash = ; //Wird von Logic gemacht
            //newUser.Salt = ; //Wird von Logic gemacht

            CustomerManager.RegisterCustomer(newCustomer, vmReg.Passwort);

            return RedirectToAction("Login");
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
                    
        [HttpPost]
        public ActionResult Login(LoginVM vmLogin)

        {
            var canLogin = CustomerManager.IsLoginValid(vmLogin.Email, vmLogin.Password);

            if (!canLogin)
            {
                return View();
            }

            //Benutzer als eingeloggt markieren
            LogUserIn(vmLogin.Email);


            return RedirectToAction("Index", "Home");
        }
       
        [HttpGet]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();

            return RedirectToAction("Index", "Home");
        }

        private void LogUserIn(string email)
        {
            FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(
                0,
                email,
                DateTime.Now,
                DateTime.Now.AddMinutes(30),
                false,
                ""
                );

            var encryptedTicket = FormsAuthentication.Encrypt(ticket);

            HttpCookie authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);

            HttpContext.Response.Cookies.Add(authCookie);
        }

       
        [HttpGet]
        public ActionResult MyOrders()
        {
            var vm = new MyOrdersVm();

            var dbOrders = OrderManager.LoadOrdersFromUser(User.Identity.Name);

            foreach (var dbOrder in dbOrders)
            {
                var orderVm = new MyOrdersVmOrder();
                orderVm.Id = dbOrder.Id;
                orderVm.OrderedAt = dbOrder.DateOrdered;
                orderVm.IsPaid = dbOrder.DatePaid == null ? false : true;
                orderVm.Total = dbOrder.PriceTotal;

                vm.Orders.Add(orderVm);
            }

            return View(vm);
        }
    }
}

NeroMerch/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meine ASP.NET-Anwendung</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @Html.Partial("_Navbar")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NeroMerch gmbH</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>
@*<script type="text/javascript">
        toastr.options = {
            "closeButton": true,
            "debug": false,
            "positionClass": "toast-top-right",
            "onclick": null,
            "showDuration": "300",
            "hideDuration": "1000",
            "timeOut": "3000",
            "extendedTimeOut": "1000",
            "showEasing": "swing",
            "showMethod": "fadeIn",
            "hideMethod": "fadeOut"
        }
        $(document).ready(function () {

            @if (TempData["ErrorMessage"] != null)
            {
                <text>
            toastr.error("", "@TempData["ErrorMessage"]");
            </text>
            }

            @if (TempData["ConfirmMessage"] != null)
            {
                <text>
            toastr.success("", "@TempData["ConfirmMessage"]");
            </text>
            }

            });
</script>*@

NeroMerch/Views/Shared/_Navbar.cshtml
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="font-size:large">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Produkte", "Overview", "Product")</li>                    

                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Impressum", "Contact", "Home")</li>
                        <li>@Html.ActionLink("AGB", "About", "Home")</li>
                        <li>@Html.ActionLink("Bestellung", "MyOrders", "Customer")</li>
                        <li style="position:absolute; left:80%">@Html.ActionLink("Warenkorb", "Show", "Cart")</li>
                        <li style="position:absolute; left:85%"><a href="/Customer/Logout">Logout</a></li>                       
                    }
                    else
                    {
                        <li style="position:absolute; left:80%;"><a href="/Customer/Login">Login</a></li>
                        <li style="position:absolute; left:85%;"><a href="/Customer/Register">Registrieren</a></li>
                    }
                </ul>                
            </div>
        </div>
    </div>
</body>
</html>

NeroMerch/Views/Shared/_PrintLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meine ASP.NET-Anwendung</title>    
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">        
        @RenderBody()        
    </div>    
    @Scripts.Render("~/bundles/jquery")    
    @Scripts.Render("~/bundles/bootstrap")    
    @RenderSection("scripts", required: false)

</body>
</html>